name: Build docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Docker tags
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            gwy15/ddpanel
            ccr.ccs.tencentyun.com/gwy15/ddpanel
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: gwy15
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to tencentyun Docker mirror
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TX_DOCKER_USER }}
          password: ${{ secrets.TX_DOCKER_PSWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
